import { PlayerBanEvent, PlayerChatEvent, PlayerIpBanEvent, PlayerIpUnBanEvent, PlayerJoinEvent, PlayerLeaveEvent, PlayerOperationUnitEvent, PlayerUnBanEvent, ServerGameOverEvent } from './event';
import { GameCommandActions, GameInternalUnits, GameOverData } from './game';
import { AbstractGameModule, HessModuleManage, PlayerHess, PlayerHessManage, ServerRoom } from './hess';
import { AbstractNetConnectServer, ServerStatus } from './server';
export declare function adaptPlayerHessManage(obj: JavaInstanceTypeOf<'net.rwhps.server.data.player.PlayerHessManage'>): PlayerHessManage;
export declare function adaptServerRoom(obj: JavaInstanceTypeOf<'net.rwhps.server.core.game.ServerRoom'>): ServerRoom;
export declare function adaptAbstractGameModule(obj: JavaInstanceTypeOf<'net.rwhps.server.game.simulation.core.AbstractGameModule'>): AbstractGameModule;
export declare function adaptHessModuleManage(obj: JavaStaticTypeOf<'net.rwhps.server.game.HessModuleManage'>): HessModuleManage;
export declare function adaptServerGameOverEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.ServerGameOverEvent'>): ServerGameOverEvent;
export declare function adaptGameOverData(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.ServerGameOverEvent$GameOverData'>): GameOverData;
export declare function adaptPlayerOpeartionUnitEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerOperationUnitEvent'>): PlayerOperationUnitEvent;
export declare function adaptPlayerLeaveEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerLeaveEvent'>): PlayerLeaveEvent;
export declare function adaptPlayerJoinEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerJoinEvent'>): PlayerJoinEvent;
export declare function adaptPlayerUnBanEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerUnBanEvent'>): PlayerUnBanEvent;
export declare function adaptPlayerIpUnBanEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerIpUnBanEvent'>): PlayerIpUnBanEvent;
export declare function adaptPlayerIpBanEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerIpBanEvent'>): PlayerIpBanEvent;
export declare function adaptPlayerChatEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerChatEvent'>): PlayerChatEvent;
export declare function adaptGameInternalUnits(obj: JavaInstanceTypeOf<'net.rwhps.server.game.enums.GameInternalUnits'>): GameInternalUnits;
export declare function adaptGameCommandActions(obj: JavaInstanceTypeOf<'net.rwhps.server.game.enums.GameCommandActions'>): GameCommandActions;
export declare function adaptServerStatus(obj: JavaInstanceTypeOf<'net.rwhps.server.net.core.DataPermissionStatus$ServerStatus'>): ServerStatus;
export declare function adaptAbstractNetConnectServer(obj: JavaInstanceTypeOf<'net.rwhps.server.net.core.server.AbstractNetConnectServer'>): AbstractNetConnectServer;
export declare function adaptPlayerHess(obj: JavaInstanceTypeOf<'net.rwhps.server.data.player.PlayerHess'>): PlayerHess;
export declare function adaptPlayerBanEvent(obj: JavaInstanceTypeOf<'net.rwhps.server.game.event.game.PlayerBanEvent'>): PlayerBanEvent;
